### ISSUE TITLE
Tempo restante

### ISSUE THREAD

**Issue by rcatechnology** [LuisFRLima/Jogos#2]
A cada tentativa, trazer o tempo restante.

![image](https://user-images.githubusercontent.com/54815598/125514874-7f70f0d7-4449-4407-831f-af8fbec052e9.png)

**Comment by LuisFRLima** [comment]
Por motivos de que o JavaScript só permiti o uso de funções de Timer limitadas(setTimeout e setInterval) ao usar essa função(no caso setTimeout) ela não me retornar a quntia de tempo
