### ISSUE TITLE
Informações básicas

### ISSUE THREAD

**Issue by rcatechnology** [LuisFRLima/Jogos#4]
Trazer quanto tempo o usuário tem pra adivinhar.
Trazer de quanto a quanto é o número que pensou.
![image](https://user-images.githubusercontent.com/54815598/125515228-ff5b9b84-ea9c-4be0-b1e6-f8f76184666f.png)

**Comment by LuisFRLima** [comment]
Trazer de quanto a quanto é o número que pensou. ja esta pronto

**Comment by LuisFRLima** [comment]
Feito
